# Generated by Django 6.0.2 on 2026-03-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmarks',
            options={'verbose_name': 'Subject Mark', 'verbose_name_plural': 'Subject Marks'},
        ),
    ]
