# Generated by Django 6.0.2 on 2026-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_alter_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
