# Generated by Django 6.0.2 on 2026-03-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_receipe_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
